import esbuild from "esbuild";
import builtins from "builtin-modules";
import fs from "node:fs";
import path from "node:path";

// 部署目标：默认你的测试库插件目录，可用环境变量 AI_TAGGER_DEPLOY_TARGET 覆盖
const TARGET =
  process.env.AI_TAGGER_DEPLOY_TARGET ||
  "E:/Notes/plugin_test/.obsidian/plugins/ai-auto-tagger";
const ROOT = process.cwd();
const ASSETS = ["main.js", "manifest.json", "styles.css"];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

function deploy() {
  try {
    fs.mkdirSync(TARGET, { recursive: true });
    for (const f of ASSETS) {
      const src = path.join(ROOT, f);
      if (fs.existsSync(src)) {
        fs.copyFileSync(src, path.join(TARGET, f));
      }
    }
    const t = new Date().toLocaleTimeString();
    console.log(`[deploy ${t}] -> ${TARGET}`);
  } catch (e) {
    console.error("[deploy error]", e.message);
  }
}

const prod = process.argv.includes("production");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [
    {
      name: "auto-deploy",
      setup(build) {
        // 每次 esbuild 重建完成（含首次）自动复制到测试库
        build.onEnd(() => deploy());
      },
    },
  ],
});

// styles.css / manifest.json 不是打包入口，单独监听它们的改动
let timer = null;
fs.watch(ROOT, (event, filename) => {
  if (filename === "styles.css" || filename === "manifest.json") {
    if (timer) clearTimeout(timer);
    timer = setTimeout(deploy, 80);
  }
});

await context.watch();
console.log(
  `\nWatching src/ + styles.css + manifest.json ...\nAuto-deploying to:\n  ${TARGET}\n(Ctrl+C to stop)\n`
);
