import esbuild from "esbuild";
import builtins from "builtin-modules";
import fs from "node:fs";
import path from "node:path";

// 部署目标：默认你的测试库插件目录，可用环境变量 AI_TAGGER_DEPLOY_TARGET 覆盖
const TARGET =
  process.env.AI_TAGGER_DEPLOY_TARGET ||
  "E:/Notes/plugin_test/.obsidian/plugins/ai-auto-tagger";
const ROOT = process.cwd();
const ASSETS = ["main.js", "manifest.json", "styles.css"];

// 默认生产构建（与 `npm run build` 一致）；传 --dev 才生成带 sourcemap 的调试版
const prod = !process.argv.includes("--dev");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

function deploy() {
  try {
    fs.mkdirSync(TARGET, { recursive: true });
    for (const f of ASSETS) {
      const src = path.join(ROOT, f);
      if (fs.existsSync(src)) {
        fs.copyFileSync(src, path.join(TARGET, f));
      }
    }
    const t = new Date().toLocaleTimeString();
    console.log(`[deploy ${t}] -> ${TARGET}`);
  } catch (e) {
    console.error("[deploy error]", e.message);
  }
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [
    {
      name: "auto-deploy",
      setup(build) {
        // 每次 esbuild 重建完成（含首次）自动复制到测试库
        build.onEnd(() => deploy());
      },
    },
  ],
});

// styles.css / manifest.json 不是打包入口，用轮询检测（比 fs.watch 在 Windows
// 上更可靠，能正确捕捉编辑器的原子保存/重命名）。每 700ms 比对 mtime。
const staticAssets = ["styles.css", "manifest.json"];
let lastMtime = {};
for (const f of staticAssets) {
  const p = path.join(ROOT, f);
  lastMtime[f] = fs.existsSync(p) ? fs.statSync(p).mtimeMs : 0;
}
setInterval(() => {
  let changed = false;
  for (const f of staticAssets) {
    const p = path.join(ROOT, f);
    if (!fs.existsSync(p)) continue;
    const m = fs.statSync(p).mtimeMs;
    if (m !== lastMtime[f]) {
      lastMtime[f] = m;
      changed = true;
    }
  }
  if (changed) deploy();
}, 700);

await context.watch();
console.log(
  `\nWatching src/ + styles.css + manifest.json ... (${prod ? "production" : "dev+sourcemap"})\n` +
    `Auto-deploying to:\n  ${TARGET}\n(Ctrl+C to stop)\n`
);
